# ---------------------------------------------------------------
# workflow: build
#
# Perform on all push and pull_request events.
# Steps will be skipped if there are no build-affecting changes
#
# * Checks all commits for compliance with conventional commit formatting
# * Builds all artifacts
# * Runs all tests
# * Runs all code checks and linters
#
# See: https://github.com/dorny/paths-filter
#
on:
  workflow_call:
    inputs:
      java-version:
        default: '17'
        description: JDK version
        required: false
        type: string
      java-distribution:
        default: 'corretto'
        description: JDK distribution
        required: false
        type: string
      force:
        default: false
        description: Force all steps (ignore changes and branch)
        required: false
        type: boolean
      skip-dependency-checks:
        default: false
        description: Skip dependency check steps
        required: false
        type: boolean

name: ci

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: gentleseal/action-conventional-commits@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-commit-types: >
            [
              "build",
              "chore",
              "docs",
              "feat",
              "fix",
              "perf",
              "refactor",
              "revert",
              "style",
              "test"
            ]

      - name: Determine branches
        id: vars
        run: |
          HEAD_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          BASE_BRANCH='master'
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV

      - name: Reject Merge Commits
        env:
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          HEAD_BRANCH: ${{ env.HEAD_BRANCH }}
        run: |
          git fetch origin $BASE_BRANCH $HEAD_BRANCH
          commits=$(git rev-list --merges origin/${{ env.BASE_BRANCH }}..origin/${{ env.HEAD_BRANCH }})
          if [ -n "$commits" ]; then
            echo "Push contains merge commits. Please rebase and remove merge commits."
            echo "Merge commits found: $commits"
            exit 1
          else
            echo "No merge commits found."
            exit 0
          fi

  changes:
    if: ${{ !startsWith(github.ref_name, 'release-please--') }}
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/src_filters.yml

  build:
    needs: [commits, changes]
    if: ${{ (inputs.force || needs.changes.outputs.src == 'true') && !startsWith(github.ref_name, 'release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ inputs.java-version }} (${{ inputs.java-distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
      - name: Build
        run: ./gradlew build
